# =========================
# PLAY 0: Ensure SSH connectivity (optional)
# =========================
- name: Ensure SSH connections can be made to all hosts
  hosts: "tag_Environment_{{ environment }}"
  gather_facts: false
  become: false
  vars:
    ansible_ssh_user: "{{ ansible_user }}"
    ansible_ssh_pass: "{{ ansible_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Test SSH connectivity
      ping:

# =========================
# PLAY 1: Deploy WAR to Tomcat
# =========================
- name: Deploy webapp to Tomcat
  hosts: "tag_Environment_{{ environment }}"
  gather_facts: false
  become: true
  vars:
    src_path: "{{ workspace_path }}/webapp/target/webapp.war"
    dest_dir: "/opt/tomcat9/webapps"
    dest_path: "{{ dest_dir }}/webapp.war"

  tasks:
    - name: Ensure Tomcat webapps directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        owner: ansibleadmin
        group: ansibleadmin
        mode: '0775'

    - name: Copy WAR file
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansibleadmin
        group: ansibleadmin
        mode: '0664'

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        enabled: true

    - name: Wait for Tomcat to start
      wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 8080
        delay: 10
        timeout: 90

    - name: Verify deployment
      uri:
        url: "http://{{ ansible_host | default(inventory_hostname) }}:8080/webapp/"
        status_code: 200
      register: result
      retries: 5
      delay: 5
      until: result.status == 200
